import BetterAuth from './notes/stack/better-auth.mdx';
import Bullmq from './notes/stack/bullmq.mdx';
import Bun from './notes/stack/bun.mdx';
import ClaudeCodeAction from './notes/stack/claude-code-action.mdx';
import DrizzleOrm from './notes/stack/drizzle-orm.mdx';
import Hono from './notes/stack/hono.mdx';
import Langfuse from './notes/stack/langfuse.mdx';
import McpTypescriptSdk from './notes/stack/mcp-typescript-sdk.mdx';
import Nextjs from './notes/stack/nextjs.mdx';
import ShadcnUi from './notes/stack/shadcn-ui.mdx';
import StrandsHarnessSdk from './notes/stack/strands-harness-sdk.mdx';
import TanstackQuery from './notes/stack/tanstack-query.mdx';
import VercelAiSdk from './notes/stack/vercel-ai-sdk.mdx';
import Vllm from './notes/stack/vllm.mdx';
import WhyThisShape from './notes/stack/why-this-shape.mdx';
import Zod from './notes/stack/zod.mdx';
import Zustand from './notes/stack/zustand.mdx';
import { stackLayout } from './stack.layout';
import type { Garden } from './types';

export const stackGarden: Garden = {
  id: 'stack',
  path: '/garden/stack',
  title: 'Stack',
  tagline: 'The tools I build with, and why each one earned its place.',
  description:
    'The stack my projects keep settling into — frontend, backend, data and AI — with the reason behind each choice rather than just a logo wall.',
  clusters: [
    { id: 'start', label: 'start here', accent: 'slate' },
    { id: 'ai', label: 'ai', accent: 'violet' },
    { id: 'frontend', label: 'frontend', accent: 'sky' },
    { id: 'backend', label: 'backend & runtime', accent: 'lime' },
    { id: 'data', label: 'data & types', accent: 'amber' },
  ],
  // Five columns fit at ~0.5, where the card text is unreadable.
  initialZoom: 0.85,
  frames: stackLayout,
  notes: [
    {
      slug: 'why-this-shape',
      title: 'Why this shape',
      summary: 'Cheap when idle, and small enough that one person can hold it in their head.',
      kind: 'note',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'start',
      tags: ['meta'],
      accent: 'slate',
      Content: WhyThisShape,
    },
    {
      slug: 'mcp-typescript-sdk',
      title: 'modelcontextprotocol / typescript-sdk',
      summary: 'The official TypeScript SDK for Model Context Protocol servers and clients.',
      kind: 'resource',
      status: 'growing',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['mcp', 'tools'],
      accent: 'violet',
      Content: McpTypescriptSdk,
    },
    {
      slug: 'vercel-ai-sdk',
      title: 'vercel / ai',
      summary: 'The AI Toolkit for TypeScript, from the creators of Next.js.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['llm', 'providers'],
      accent: 'violet',
      Content: VercelAiSdk,
    },
    {
      slug: 'langfuse',
      title: 'langfuse / langfuse',
      summary: 'Open source AI engineering platform: LLM evals, observability, metrics, prompt management.',
      kind: 'resource',
      status: 'seed',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['evals', 'observability'],
      accent: 'violet',
      Content: Langfuse,
    },
    {
      slug: 'strands-harness-sdk',
      title: 'strands-agents / harness-sdk',
      summary: 'Build an agent harness and control it end-to-end.',
      kind: 'resource',
      status: 'seed',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['agents'],
      accent: 'violet',
      Content: StrandsHarnessSdk,
    },
    {
      slug: 'vllm',
      title: 'vllm-project / vllm',
      summary: 'A high-throughput and memory-efficient inference and serving engine for LLMs.',
      kind: 'resource',
      status: 'seed',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['inference', 'self-hosting'],
      accent: 'violet',
      Content: Vllm,
    },
    {
      slug: 'claude-code-action',
      title: 'anthropics / claude-code-action',
      summary: 'Claude Code as a GitHub Action.',
      kind: 'resource',
      status: 'seed',
      updated: '2026-08-28',
      cluster: 'ai',
      tags: ['ci', 'agents'],
      accent: 'violet',
      Content: ClaudeCodeAction,
    },
    {
      slug: 'nextjs',
      title: 'vercel / next.js',
      summary: 'The React Framework.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'frontend',
      tags: ['react', 'rsc'],
      accent: 'sky',
      Content: Nextjs,
    },
    {
      slug: 'shadcn-ui',
      title: 'shadcn-ui / ui',
      summary: 'A set of beautifully-designed, accessible components and a code distribution platform.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'frontend',
      tags: ['components', 'radix'],
      accent: 'sky',
      Content: ShadcnUi,
    },
    {
      slug: 'zustand',
      title: 'pmndrs / zustand',
      summary: 'Bear necessities for state management in React.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'frontend',
      tags: ['state'],
      accent: 'sky',
      Content: Zustand,
    },
    {
      slug: 'tanstack-query',
      title: 'TanStack / query',
      summary: 'Powerful asynchronous state management, server-state utilities and data fetching.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'frontend',
      tags: ['data-fetching'],
      accent: 'sky',
      Content: TanstackQuery,
    },
    {
      slug: 'hono',
      title: 'honojs / hono',
      summary: 'Web framework built on Web Standards.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'backend',
      tags: ['workers', 'router'],
      accent: 'lime',
      Content: Hono,
    },
    {
      slug: 'bun',
      title: 'oven-sh / bun',
      summary: 'Incredibly fast JavaScript runtime, bundler, test runner and package manager.',
      kind: 'resource',
      status: 'growing',
      updated: '2026-08-28',
      cluster: 'backend',
      tags: ['runtime', 'tooling'],
      accent: 'lime',
      Content: Bun,
    },
    {
      slug: 'better-auth',
      title: 'better-auth / better-auth',
      summary: 'The most comprehensive authentication framework.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'backend',
      tags: ['auth', 'sessions'],
      accent: 'lime',
      Content: BetterAuth,
    },
    {
      slug: 'bullmq',
      title: 'taskforcesh / bullmq',
      summary: 'Message queue and batch processing for Node.js, built on Redis.',
      kind: 'resource',
      status: 'growing',
      updated: '2026-08-28',
      cluster: 'backend',
      tags: ['queues', 'redis'],
      accent: 'lime',
      Content: Bullmq,
    },
    {
      slug: 'drizzle-orm',
      title: 'drizzle-team / drizzle-orm',
      summary: 'Typed SQL ORM with no codegen step.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'data',
      tags: ['sql', 'types'],
      accent: 'amber',
      Content: DrizzleOrm,
    },
    {
      slug: 'zod',
      title: 'colinhacks / zod',
      summary: 'TypeScript-first schema validation with static type inference.',
      kind: 'resource',
      status: 'evergreen',
      updated: '2026-08-28',
      cluster: 'data',
      tags: ['validation', 'types'],
      accent: 'amber',
      Content: Zod,
    },
  ],
};
